/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



int main(void)

{

	//RCC Clock Enable
	uint32_t *RCC_AHB1 = (uint32_t*)(0x40023800 + 0x30);
	*RCC_AHB1 |= (1<<1);



	//GPIOB MODER Enable
	uint32_t *GPIOB_MODER = (uint32_t*) (0x40020400);
	*GPIOB_MODER &= 0xFFFFFFF3;
	*GPIOB_MODER |= (1<<2);

	//OUTPUT Enable
	uint32_t *GPIOB_ODR = (uint32_t*)(0x40020400 + 0x14);

	while(1){
		for(volatile uint32_t i = 0;i<1000000;i++)
			*GPIOB_ODR |= (1<<1);  //LED ON

		for(volatile uint32_t i = 0; i<1000000;i++)
			*GPIOB_ODR &= ~(1<<1);  //LED OFF
	}




    /* Loop forever */
	for(;;);
}
