/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	// ================PUSH BUTTON SECTION =====================

	//Clock Enable for push button
	uint32_t *RCC_AHB1 = (uint32_t*)(0x40023800 + 0x30);
	*RCC_AHB1 |= (1<<2);


	//Input State declaration
	uint32_t *GPIOC_IDR = (uint32_t*)(0x40020800 + 0x10);


	//GPIOC Enable
	uint32_t *GPIOC_MODER = (uint32_t*)(0x40020800);
	*GPIOC_MODER &= ~(0x03 <<20);





    // ============== INTERNAL PULL UP RESISOTR ===================

	uint32_t *GPIOC_PUPDR = (uint32_t*)(0x40020800 + 0x0C);

	*GPIOC_PUPDR &= ~(0x03 << 20);  // clear bits 21:20
	*GPIOC_PUPDR |=  (0x01 << 20);  // 01 = pull-up



	// ================= LED SECTION ===================

	//RCC Clock Enable for led
	uint32_t *RCC_AHB1_LED = (uint32_t*)(0x40023800 + 0x30);
	*RCC_AHB1_LED |= (1<<1);


	//GPIOB MODER Enable
	uint32_t *GPIOB_MODER = (uint32_t*) (0x40020400);
	*GPIOB_MODER &= 0xFFFFFFF3;
	*GPIOB_MODER |= (1<<2);


	//OUTPUT Enable
	uint32_t *GPIOB_ODR = (uint32_t*)(0x40020400 + 0x14);


	//MAIN LOOPS FOREVER RUNS
	for(;;){

		// ========= BUTTON PRESS LOGIC ===============
		if(((*GPIOC_IDR) & (1<<10)) ==0){
			*GPIOB_ODR |= (1<<1);  //LED ON
		}
		else{
			*GPIOB_ODR &= ~(1<<1);  //LED OFF
		}
	}
}
