/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)

{
//	uint32_t *RCC_GPIOD = (uint32_t*) (0x40023800 + 0x30);
//	*RCC_GPIOD |= 0x01<<3;
//
//	uint32_t *gpiod_moder = (uint32_t*) (0x40020C00);
//	*gpiod_moder &= 0xF3FFFFFF;    //1111 0011 1111 1111 1111 1111 1111 1111
//	*gpiod_moder |= 0x01<<26;
//
//
//	uint32_t *gpiod_state = (uint32_t*) (0x40020C00 + 0x14);
//
//
//    /* Loop forever */
//	while(1){
//		for(volatile uint32_t i = 0;i<1000000;i++){
//			*gpiod_state |= 0x01<<13;  //ON LED
//
//		}
//
//		for(volatile uint32_t i = 0;i<1000000;i++){
//			*gpiod_state &= ~(0x01<<13);  //OFF LED
//
//
//		}
//	}




	for(;;);

}
